function [VV,FF] = subdivided_weirdshape(N)
%SUBDIVIDED_WEIRDSHAPE Smooth strange closed shape centered at the origin
%
%   [VV,FF] = subdivided_weirdshape(N)
%
% Input:
%   N  - subdivision level (positive integer)
%
% Output:
%   VV - vertices
%   FF - triangular faces
%
% The mesh is generated by subdividing an icosahedron, projecting to the
% sphere, then applying a smooth radial deformation.

if N < 1 || round(N) ~= N
    error('N must be a positive integer.');
end

% Icosahedron coordinates
t = (1+sqrt(5))/2;
V = 1/sqrt(1+t^2) * ...
    [ t  1  0;
     -t  1  0;
      t -1  0;
     -t -1  0;
      1  0  t;
      1  0 -t;
     -1  0  t;
     -1  0 -t;
      0  t  1;
      0 -t  1;
      0  t -1;
      0 -t -1];

F = [ ...
    1  9  5;  1  6 11;  3  5 10;  3 12  6; ...
    2  7  9;  2 11  8;  4 10  7;  4  8 12; ...
    1 11  9;  2  9 11;  3 10 12;  4 12 10; ...
    5  3  1;  6  1  3;  7  2  4;  8  4  2; ...
    9  7  5; 10  5  7; 11  6  8; 12  8  6];

VV = [];
FF = [];

% Subdivide each face into triangles
for i = 1:size(F,1)

    v1 = V(F(i,1),:);
    v2 = V(F(i,2),:);
    v3 = V(F(i,3),:);

    c = 0;
    v123 = [];

    for j = 0:N
        v12 = (v1*(N-j) + v2*j)/N;
        v13 = (v1*(N-j) + v3*j)/N;

        for k = 0:j
            c = c + 1;
            if j == 0
                v123(c,:) = v12;
            else
                v123(c,:) = (v12*(j-k) + v13*k)/j;
            end
        end
    end

    c = 0;
    FT = [];

    for j = 1:N
        for k = 1:j
            c = c + 1;
            n = j*(j-1)/2 + k;
            FT(c,:) = [n, n+j, n+j+1];
        end
    end

    for j = 2:N
        for k = 1:j-1
            c = c + 1;
            n = j*(j-1)/2 + k;
            FT(c,:) = [n, n+j+1, n+1];
        end
    end

    m  = size(VV,1);
    VV = [VV; v123];
    FF = [FF; FT + m];
end

% Remove duplicate vertices
tol = 1e-10;
[VV,~,ix] = uniquetol(VV, tol, 'ByRows', true);
FF = ix(FF);

% Project to unit sphere
for i = 1:size(VV,1)
    VV(i,:) = VV(i,:) / norm(VV(i,:));
end

% Smooth weird radial deformation
x = VV(:,1);
y = VV(:,2);
z = VV(:,3);

r = 1 ...
    + 0.28*sin(3*x + 2*y - z) ...
    + 0.18*cos(4*z - 2*x) ...
    + 0.12*sin(5*(x.*y)) ...
    + 0.10*cos(6*(y.*z)) ...
    - 0.08*sin(4*(z.*x));

% Keep shape safely star-shaped / closed
r = max(r, 0.35);

VV = VV .* r;

% Recenter exactly at origin
VV = VV - mean(VV,1);

% Optional rescale to O(1) size
rad = max(vecnorm(VV,2,2));
VV = VV / rad;

end