function [results, density_comparison] = test_project_surface_constraints(output_dir)
%TEST_PROJECT_SURFACE_CONSTRAINTS Regression tests for constraint projection.
%
%   [results,density_comparison] = test_project_surface_constraints()
%
% The tests are independent of remeshing. They exercise volume-only and
% simultaneous area/volume projection, and compare mass and Euclidean
% weighting on a deliberately nonuniform sphere.

    if nargin < 1 || isempty(output_dir)
        output_dir = fullfile(fileparts(mfilename("fullpath")), "data", ...
            "adaptive_remeshing_diagnostics");
    end
    if ~isfolder(output_dir)
        mkdir(output_dir);
    end

    projection_options = struct( ...
        "tol_area", 1e-11, ...
        "tol_volume", 1e-11, ...
        "max_iter", 20, ...
        "max_step_edge_fraction", 0.2, ...
        "verbose", false);

    cases = make_test_cases();
    rows = repmat(empty_result_row(), 0, 1);
    for case_index = 1:numel(cases)
        test_case = cases(case_index);
        for weighting = ["mass", "euclidean"]
            options = projection_options;
            options.weighting = weighting;
            options.preserve_area = test_case.preserve_area;
            options.preserve_volume = test_case.preserve_volume;
            [P_fixed, ~, info] = project_surface_constraints( ...
                test_case.P_perturbed, test_case.M, test_case.targets, options);
            diagnostics = mesh_surface_diagnostics(test_case.M, P_fixed);
            row = empty_result_row();
            row.case_name = test_case.name;
            row.weighting = weighting;
            row.converged = info.converged;
            row.iterations = info.iterations;
            row.rel_area_error_initial = info.rel_area_error_initial;
            row.rel_volume_error_initial = info.rel_volume_error_initial;
            row.rel_area_error_final = info.rel_area_error;
            row.rel_volume_error_final = info.rel_volume_error;
            row.max_displacement = info.max_displacement;
            row.rms_displacement = info.rms_displacement;
            row.min_triangle_angle_deg = diagnostics.min_triangle_angle_deg;
            row.max_triangle_aspect_ratio = diagnostics.max_aspect_ratio;
            row.valid_mesh = diagnostics.valid;
            rows(end + 1, 1) = row; %#ok<AGROW>

            assert(info.converged, ...
                "%s/%s projection did not converge: %s", ...
                test_case.name, weighting, info.reason);
            assert(diagnostics.valid, "%s/%s produced an invalid mesh.", ...
                test_case.name, weighting);
            if test_case.preserve_area
                assert(info.rel_area_error <= 2 * projection_options.tol_area);
            end
            if test_case.preserve_volume
                assert(info.rel_volume_error <= 2 * projection_options.tol_volume);
            end
        end
    end
    results = struct2table(rows);

    density_comparison = compare_nonuniform_sphere(projection_options);
    assert(density_comparison.normal_displacement_cv(1) ...
        < 0.2 * density_comparison.normal_displacement_cv(2), ...
        "Mass weighting did not sufficiently reduce mesh-density dependence.");

    writetable(results, fullfile(output_dir, "constraint_projection_tests.csv"));
    writetable(density_comparison, ...
        fullfile(output_dir, "nonuniform_sphere_weighting.csv"));
    save(fullfile(output_dir, "constraint_projection_tests.mat"), ...
        "results", "density_comparison");

    fprintf("\nConstraint projection tests\n");
    disp(results(:, ["case_name", "weighting", "iterations", ...
        "rel_area_error_final", "rel_volume_error_final", ...
        "max_displacement"]));
    fprintf("Nonuniform sphere weighting comparison (vertex-area ratio %.1f)\n", ...
        density_comparison.vertex_area_ratio(1));
    disp(density_comparison(:, ["weighting", "normal_displacement_cv", ...
        "area_displacement_correlation", "rel_volume_error_final"]));
end

function cases = make_test_cases()
    [sphere_P, sphere_M] = subdivided_sphere(7);
    sphere_P = sphere_P ./ vecnorm(sphere_P, 2, 2);
    sphere_geo = Geometry(sphere_M, sphere_P);
    cases(1) = struct( ...
        "name", "uniform_sphere_volume", ...
        "M", sphere_M, ...
        "P_perturbed", 1.01 * sphere_P, ...
        "targets", struct("volume", sphere_geo.volume), ...
        "preserve_area", false, ...
        "preserve_volume", true);

    spheroid_P = sphere_P .* [1.55, 0.82, 0.82];
    spheroid_geo = Geometry(sphere_M, spheroid_P);
    x_scaled = spheroid_P(:, 1) / max(abs(spheroid_P(:, 1)));
    spheroid_delta = 0.035 * mean(spheroid_geo.he_length) ...
        * (0.35 + x_scaled.^2);
    cases(2) = struct( ...
        "name", "spheroid_area_volume", ...
        "M", sphere_M, ...
        "P_perturbed", spheroid_P + spheroid_delta .* spheroid_geo.v_normal, ...
        "targets", struct("area", spheroid_geo.area, ...
            "volume", spheroid_geo.volume), ...
        "preserve_area", true, ...
        "preserve_volume", true);

    [dumbbell_M, dumbbell_P] = initial_dumbbell(0.35, [24, 48]);
    dumbbell_geo = Geometry(dumbbell_M, dumbbell_P);
    x_scaled = dumbbell_P(:, 1) / max(abs(dumbbell_P(:, 1)));
    dumbbell_delta = 0.025 * mean(dumbbell_geo.he_length) ...
        * (0.25 + cos(pi * x_scaled).^2);
    cases(3) = struct( ...
        "name", "tubular_dumbbell_area_volume", ...
        "M", dumbbell_M, ...
        "P_perturbed", dumbbell_P + dumbbell_delta .* dumbbell_geo.v_normal, ...
        "targets", struct("area", dumbbell_geo.area, ...
            "volume", dumbbell_geo.volume), ...
        "preserve_area", true, ...
        "preserve_volume", true);
end

function comparison = compare_nonuniform_sphere(base_options)
    [P, M] = subdivided_sphere(9);
    P = P ./ vecnorm(P, 2, 2);
    P = conformal_sphere_concentration(P, 0.85);
    geo_target = Geometry(M, P);
    P_perturbed = 1.01 * P;
    geo_perturbed = Geometry(M, P_perturbed);
    targets = struct("volume", geo_target.volume);

    rows = repmat(struct(), 2, 1);
    weightings = ["mass", "euclidean"];
    for index = 1:numel(weightings)
        options = base_options;
        options.weighting = weightings(index);
        options.preserve_area = false;
        options.preserve_volume = true;
        [P_fixed, ~, info] = project_surface_constraints( ...
            P_perturbed, M, targets, options);
        displacement = P_fixed - P_perturbed;
        normal_displacement = abs(dot(displacement, geo_perturbed.v_normal, 2));
        rows(index).weighting = weightings(index);
        rows(index).vertex_area_ratio = max(geo_perturbed.v_area) ...
            / min(geo_perturbed.v_area);
        rows(index).normal_displacement_mean = mean(normal_displacement);
        rows(index).normal_displacement_cv = std(normal_displacement) ...
            / mean(normal_displacement);
        rows(index).area_displacement_correlation = correlation_coefficient( ...
            geo_perturbed.v_area, normal_displacement);
        rows(index).rel_volume_error_final = info.rel_volume_error;
        rows(index).iterations = info.iterations;
    end
    comparison = struct2table(rows);
end

function P = conformal_sphere_concentration(P, amount)
% A Mobius transformation of the sphere; exact points remain on r=1.
    denominator = 1 + amount * P(:, 3);
    transverse_scale = sqrt(1 - amount^2);
    P = [transverse_scale * P(:, 1) ./ denominator, ...
        transverse_scale * P(:, 2) ./ denominator, ...
        (P(:, 3) + amount) ./ denominator];
    P = P ./ vecnorm(P, 2, 2);
end

function value = correlation_coefficient(x, y)
    x = x(:) - mean(x);
    y = y(:) - mean(y);
    value = dot(x, y) / max(norm(x) * norm(y), realmin);
end

function row = empty_result_row()
    row = struct( ...
        "case_name", "", ...
        "weighting", "", ...
        "converged", false, ...
        "iterations", 0, ...
        "rel_area_error_initial", NaN, ...
        "rel_volume_error_initial", NaN, ...
        "rel_area_error_final", NaN, ...
        "rel_volume_error_final", NaN, ...
        "max_displacement", NaN, ...
        "rms_displacement", NaN, ...
        "min_triangle_angle_deg", NaN, ...
        "max_triangle_aspect_ratio", NaN, ...
        "valid_mesh", false);
end
