function results = test_mmgs_backend(output_dir)
%TEST_MMGS_BACKEND Controlled regression tests for the MMGS MEX backend.

    if nargin < 1 || isempty(output_dir)
        output_dir = fullfile(fileparts(mfilename("fullpath")), "data", ...
            "adaptive_remeshing_diagnostics");
    end
    if ~isfolder(output_dir)
        mkdir(output_dir);
    end

    [P, M] = subdivided_sphere(10);
    P = P ./ vecnorm(P, 2, 2);
    target_h = 0.18 - 0.09 * tanh(3 * P(:, 3));
    options = struct( ...
        "backend", "mmgs", ...
        "match_target_complexity", true, ...
        "vertex_count_tolerance", 0.08, ...
        "hausdorff_factor", 0.2);
    [P2, M2, info] = remesh_surface(P, M, target_h, options);

    edges = unique(sort([M2(:, [1, 2]); M2(:, [2, 3]); ...
        M2(:, [3, 1])], 2), "rows");
    edge_length = vecnorm(P2(edges(:, 2), :) - P2(edges(:, 1), :), 2, 2);
    edge_z = 0.5 * (P2(edges(:, 1), 3) + P2(edges(:, 2), 3));
    north_median = median(edge_length(edge_z > 0.4));
    south_median = median(edge_length(edge_z < -0.4));

    results = table( ...
        size(P, 1), ...
        info.status.target_vertex_count, ...
        size(P2, 1), ...
        info.status.vertex_count_relative_error, ...
        info.status.complexity_passes, ...
        north_median, ...
        south_median, ...
        north_median / south_median, ...
        info.raw_after.min_triangle_angle_deg, ...
        info.raw_after.max_aspect_ratio, ...
        info.raw_after.closed, ...
        info.raw_after.orientation_consistent, ...
        'VariableNames', { ...
        'n_vertices_before', 'n_vertices_target', 'n_vertices_after', ...
        'vertex_count_relative_error', 'complexity_passes', ...
        'fine_region_median_edge', 'coarse_region_median_edge', ...
        'fine_to_coarse_edge_ratio', 'min_triangle_angle_deg', ...
        'max_aspect_ratio', 'closed', 'orientation_consistent'});

    assert(info.raw_after.valid, "MMGS produced an invalid surface mesh.");
    assert(results.vertex_count_relative_error <= options.vertex_count_tolerance);
    assert(results.fine_to_coarse_edge_ratio < 0.7, ...
        "MMGS output did not respond sufficiently to the supplied size field.");

    writetable(results, fullfile(output_dir, "mmgs_controlled_test.csv"));
    save(fullfile(output_dir, "mmgs_controlled_test.mat"), ...
        "results", "P", "M", "target_h", "P2", "M2", "info");
    fprintf("\nControlled MMGS size-field test\n");
    disp(results);
end
